export const LOGIN = "LOGIN";
export const LOGIN_FAILUER = "LOGIN_FAILUER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILUER = "REGISTER_FAILUER";

export const LOADING = "LOADING";

export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";

export const CREATE_CONTACT = "CREATE_CONTACT";
export const CREATE_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";
export const CREATE_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const RESET_STATE = "RESET_STATE";
export const LOADING_CONTACTS = "LOADING_CONTACTS";

export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";
